### ISSUE TITLE
Wanneer maak je het af?

### ISSUE THREAD

**Issue by Stukongeluk** [bobsoppe/site-bobsoppe.nl#1]
Ik zie dat je 6 dagen geleden voor het laatst een commit hebt gemaakt.
# Wanneer maak je het af?

**Comment by bobsoppe** [comment]
6

**Comment by Stukongeluk** [comment]
![image](https://user-images.githubusercontent.com/9076248/32554317-aff744ea-c499-11e7-814e-9083c3c51488.png)
dafuq
